name: CI Pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          auto-activate-base: false
          miniconda-version: "latest"
          environment-file: conda.yaml

      - name: Update Conda environment
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda env update -n forecasting-env -f conda.yaml --prune
          
      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          conda activate forecasting-env
          mlflow run . \
            --experiment-name github-ci \
            --run-name ci_run_${{ github.run_number }}